/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.intellipix;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int solid_blue=0x7f050001;
        public static final int solid_green=0x7f050002;
        public static final int solid_red=0x7f050000;
        public static final int solid_yellow=0x7f050003;
    }
    public static final class drawable {
        public static final int add_content64x64=0x7f020000;
        public static final int alert_dialog_icon=0x7f020001;
        public static final int audio=0x7f020002;
        public static final int audio_mime_type48x48=0x7f020003;
        public static final int black_box=0x7f020004;
        public static final int blank48x48=0x7f020005;
        public static final int blue=0x7f02001b;
        public static final int camera=0x7f020006;
        public static final int camera_graphic=0x7f020007;
        public static final int cancel=0x7f020008;
        public static final int caption_mime_type48x48=0x7f020009;
        public static final int date_mime_type48x48=0x7f02000a;
        public static final int disk=0x7f02000b;
        public static final int enhanced48x48=0x7f02000c;
        public static final int filled_box=0x7f02000d;
        public static final int green=0x7f02001c;
        public static final int icon=0x7f02000e;
        public static final int intellipixsm=0x7f02000f;
        public static final int inventory64x64=0x7f020010;
        public static final int makesmarter=0x7f020011;
        public static final int map=0x7f020012;
        public static final int map_mime_type48x48=0x7f020013;
        public static final int ok=0x7f020014;
        public static final int preview=0x7f020015;
        public static final int red=0x7f02001a;
        public static final int red_pushpin=0x7f020016;
        public static final int remove=0x7f020017;
        public static final int remove_content64x64=0x7f020018;
        public static final int save64x64=0x7f020019;
        public static final int screen_background_black=0x7f02001e;
        public static final int translucent_background=0x7f02001f;
        public static final int transparent_background=0x7f020020;
        public static final int yellow=0x7f02001d;
    }
    public static final class id {
        public static final int add_content=0x7f080007;
        public static final int add_content_linear_layout=0x7f080001;
        public static final int audio=0x7f080003;
        public static final int camera=0x7f080020;
        public static final int cancel_button=0x7f08000f;
        public static final int caption_entry_linear=0x7f08000b;
        public static final int caption_label=0x7f08000c;
        public static final int captionedittext=0x7f08000d;
        public static final int disk=0x7f08001f;
        public static final int icon=0x7f080012;
        public static final int imagePreview=0x7f08000a;
        public static final int intellipixsm=0x7f08001e;
        public static final int inventory_folder=0x7f080006;
        public static final int latedittext=0x7f080016;
        public static final int latitude_label=0x7f080015;
        public static final int linear_layout=0x7f08001d;
        public static final int longedittext=0x7f080018;
        public static final int longitude_label=0x7f080017;
        public static final int main_top_level_layout=0x7f080005;
        public static final int makesmarter=0x7f080002;
        public static final int map=0x7f080004;
        public static final int map_entry_linear=0x7f080014;
        public static final int map_entry_preview=0x7f080019;
        public static final int message=0x7f080011;
        public static final int ok_button=0x7f080010;
        public static final int okcancel_layout=0x7f08000e;
        public static final int remove_content=0x7f080008;
        public static final int save=0x7f080009;
        public static final int save_file_entry_linear=0x7f08001a;
        public static final int save_label=0x7f08001b;
        public static final int saveedittext=0x7f08001c;
        public static final int table_layout=0x7f080000;
        public static final int text=0x7f080013;
    }
    public static final class layout {
        public static final int addcontent=0x7f030000;
        public static final int assemble=0x7f030001;
        public static final int caption_entry=0x7f030002;
        public static final int caption_panel=0x7f030003;
        public static final int list_item_icon_text=0x7f030004;
        public static final int map_entry=0x7f030005;
        public static final int map_view=0x7f030006;
        public static final int save_file_entry=0x7f030007;
        public static final int translucent_background=0x7f030008;
        public static final int welcome=0x7f030009;
    }
    public static final class raw {
        public static final int dean1=0x7f040000;
    }
    public static final class string {
        public static final int activity_translucent=0x7f060005;
        public static final int add_caption=0x7f060012;
        public static final int add_content=0x7f060011;
        public static final int add_map=0x7f060013;
        public static final int alert_dialog_ok=0x7f060008;
        public static final int app_name=0x7f060000;
        public static final int assemble_review=0x7f060004;
        public static final int audio_mime_type=0x7f06000a;
        public static final int caption_mime_type=0x7f06000d;
        public static final int date_mime_type=0x7f060018;
        public static final int default_image=0x7f060002;
        public static final int delete_file=0x7f060017;
        public static final int inventory=0x7f060006;
        public static final int inventory_select=0x7f060016;
        public static final int load_photo=0x7f060001;
        public static final int loading_files=0x7f060009;
        public static final int map=0x7f06000b;
        public static final int map_entry_usage=0x7f060010;
        public static final int map_mime_type=0x7f06000c;
        public static final int no_brain=0x7f06000e;
        public static final int no_compatable_files_found=0x7f060007;
        public static final int record=0x7f060003;
        public static final int remove_content=0x7f06000f;
        public static final int select_photo=0x7f060015;
        public static final int take_picture=0x7f060014;
    }
    public static final class style {
        public static final int TextAppearance_Theme_PlainText=0x7f070006;
        /**  Base application theme is the default theme. 
         */
        public static final int Theme=0x7f070000;
        /**  Variation on our application theme that has a black
         background. 
         */
        public static final int Theme_Black=0x7f070002;
        /**  A theme for a custom dialog appearance.  Here we use an ugly
         custom frame. 
         */
        public static final int Theme_CustomDialog=0x7f070003;
        /**  Variation on our application theme that forces a plain
        text style. 
         */
        public static final int Theme_PlainText=0x7f070001;
        /**  A theme that has a translucent background.  Here we explicitly specify
         that this theme is to inherit from the system's translucent theme,
         which sets up various attributes correctly.. 
         */
        public static final int Theme_Translucent=0x7f070004;
        /**  Variation on our application theme that has a transparent
         background; this example completely removes the background,
         allowing the activity to decide how to composite.  Also here we
         force the translucency ourself rather than making use of the built-in
         translucent theme. 
         */
        public static final int Theme_Transparent=0x7f070005;
    }
}
